// export const toAdd = (keys: string, values: number) => ({ type: 'postData', value: values, key: keys });
export const chooseSong = (value: number) => ({ type: 'CHOOSE_MUSIC', index: value })
export const toggleSong = () => ({ type: 'TOGGLE_PLAY' })
export const startSong = () => ({ type: 'START_SONG' })
export const pauseSong = () => ({ type: 'PAUSE_SONG' })
export const follow = () => ({ type: 'FOLLOW' })
export const updateMode = (value: string) => ({ type: 'UPDATE_MODE', message: value })
export const changeAlbum = (value: number) => ({ type: 'CHANGE_ALBUM', index: value })
export const premium = () => ({ type: 'GO_PREMIUM' })
export const handleAdvertise = (value: boolean) => ({ type: 'CHANGE_ADVERTISE_STATE', state: value })
export const handleBar = (value: boolean) => ({ type: 'CHANGE_BAR_STATE', state: value })
